name: Build and Push Docker Image

on:
  push:
    branches:
      - main
env:
  #REGISTRY_NAME: <your-acr-registry>  # replace with your ACR name
  IMAGE_NAME: python-talib  # replace with your Docker image name

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          
      - name: Login and Push to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}  # stored in GitHub Secrets
          password: ${{ secrets.REGISTRY_PASSWORD }}  # stored in GitHub Secrets
      
      # Generate the current date in YYYYMMDD format
      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
        
      
            
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
