name: Build and Push Docker Image

on:
  push:
    branches:
      - main
env:
  #REGISTRY_NAME: <your-acr-registry>  # replace with your ACR name
  IMAGE_NAME: python-talib  # replace with your Docker image name

permissions:
  packages: write


jobs:
            build-and-push:
              runs-on: ubuntu-latest
              steps:
              - name: Checkout repository
                uses: actions/checkout@v2

              - name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                
              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
                with:
                  buildkitd-flags: --debug
              - name: Login to ACR
                uses: azure/docker-login@v1
                with:
                  login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.REGISTRY_USERNAME }}  # stored in GitHub Secrets
                  password: ${{ secrets.REGISTRY_PASSWORD }}  # stored in GitHub Secrets
          
              
              
            armv7_job:
                # The host should always be Linux
                runs-on: ubuntu-22.04
                name: Build on ubuntu-22.04 armv7
                steps:
                  - uses: actions/checkout@v4
                  - uses: uraimo/run-on-arch-action@v2
                    name: Run commands
                    id: runcmd
                    with:
                      arch: armv7
                      distro: ubuntu22.04
            
                      
            
                      # Set an output parameter `uname` for use in subsequent steps
                      run: |
                        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
                        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest